apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: sylse/auth-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mso-secrets
                  key: db_root_password
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: db_user
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: db_host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: auth_db_name

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: auth-service
  type: ClusterIP
